<a href="https://colab.research.google.com/github/nikolayninov/tensorflow/blob/master/IBM/Introduction_to_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
graph1 = tf.Graph()

In [0]:
with graph1.as_default():
  a = tf.constant([2], name="constant_a")
  b = tf.constant([3], name="constant_b") 
 

In [5]:
a


<tf.Tensor 'constant_a:0' shape=(1,) dtype=int32>

In [8]:
sess = tf.Session(graph = graph1)
result = sess.run(a)
print(result)
sess.close()

[2]


In [0]:
with graph1.as_default():
  c = tf.add(a,b)

In [11]:
sess = tf.Session(graph = graph1)
result = sess.run(c)
print(result)
sess.close()

[5]


In [12]:
# Multidimensional arrays using TensorFlow

graph2 = tf.Graph()

with graph2.as_default():
  Scalar = tf.constant(2)
  Vector = tf.constant([5,6,2])
  Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
  Tensor = tf.constant([ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ])
with tf.Session(graph = graph2) as sess:
  result = sess.run(Scalar)
  print ("Scalar (1 entry):\n %s \n" % result)
  result = sess.run(Vector)
  print ("Vector (3 entries) :\n %s \n" % result)
  result = sess.run(Matrix)
  print ("Matrix (3x3 entries):\n %s \n" % result)
  result = sess.run(Tensor)
  print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 2 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [20]:
with graph2.as_default():
  print(Scalar.shape)



()


In [21]:
graph3 = tf.Graph()

with graph3.as_default():
  Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
  Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])
  
  add_1_operation = tf.add(Matrix_one,Matrix_two)
  add_2_operation = Matrix_one + Matrix_two
  
with tf.Session(graph = graph3) as sess:
  result = sess.run(add_1_operation)
  print ("Defined using tensorflow function :")
  print(result)
  result = sess.run(add_2_operation)
  print ("Defined using normal expressions :")
  print(result)

Defined using tensorflow function :
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using normal expressions :
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [22]:
graph4 = tf.Graph()
with graph4.as_default():
    Matrix_one = tf.constant([[2,3],[3,4]])
    Matrix_two = tf.constant([[2,3],[3,4]])

    mul_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session(graph = graph4) as sess:
    result = sess.run(mul_operation)
    print ("Defined using tensorflow function :")
    print(result)

Defined using tensorflow function :
[[13 18]
 [18 25]]


#Variables

To define variables we use the command **tf.Variable()**. To be able to use variables in a computation graph it is necessary to initialize them before running the graph in a session. This is done by running **tf.global_variables_initializer()**.


In [0]:
v = tf.Variable(0)

In [0]:
update = tf.assign(v, v+1)

In [0]:
init_op = tf.global_variables_initializer()

In [29]:
with tf.Session() as sess:
  sess.run(init_op)
  print(sess.run(v))
  for _ in range(3):
    sess.run(update)
    print(sess.run(v))

0
1
2
3


#Placeholders

If you want to feed data to a TensorFlow graph from outside a graph, you will need to use placeholders.

So <b>what are these placeholders and what do they do?</b> 

Placeholders can be seen as "holes" in your model, "holes" which you will pass the data to, you can create them using <br> <b>tf.placeholder(_datatype_)</b>, where <b>_datatype_</b> specifies the type of data (integers, floating points, strings, booleans) along with its precision (8, 16, 32, 64) bits.

The definition of each data type with the respective python syntax is defined as:

|Data type	|Python type|Description|
| --------- | --------- | --------- |
|DT_FLOAT	|tf.float32	|32 bits floating point.|
|DT_DOUBLE	|tf.float64	|64 bits floating point.|
|DT_INT8	|tf.int8	|8 bits signed integer.|
|DT_INT16	|tf.int16	|16 bits signed integer.|
|DT_INT32	|tf.int32	|32 bits signed integer.|
|DT_INT64	|tf.int64	|64 bits signed integer.|
|DT_UINT8	|tf.uint8	|8 bits unsigned integer.|
|DT_STRING	|tf.string	|Variable length byte arrays. Each element of a Tensor is a byte array.|
|DT_BOOL	|tf.bool	|Boolean.|
|DT_COMPLEX64	|tf.complex64	|Complex number made of two 32 bits floating points: real and imaginary parts.|
|DT_COMPLEX128	|tf.complex128	|Complex number made of two 64 bits floating points: real and imaginary parts.|
|DT_QINT8	|tf.qint8	|8 bits signed integer used in quantized Ops.|
|DT_QINT32	|tf.qint32	|32 bits signed integer used in quantized Ops.|
|DT_QUINT8	|tf.quint8	|8 bits unsigned integer used in quantized Ops.|


In [0]:
a = tf.placeholder(tf.float32)

In [0]:
b = a*2

In [34]:
with tf.Session() as sess:
  result = sess.run(b,feed_dict={a:3.5})
  print(result)

7.0


In [0]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

In [36]:
with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


<a id="ref8"></a>
<hr>Operations</h2>

Operations are nodes that represent the mathematical operations over the tensors on a graph. These operations can be any kind of functions, like add and subtract tensor or maybe an activation function.

<b>tf.constant</b>, <b>tf.matmul</b>, <b>tf.add</b>, <b>tf.nn.sigmoid</b> are some of the operations in TensorFlow. These are like functions in python but operate directly over tensors and each one does a specific thing. 


In [37]:
graph5 = tf.Graph()
with graph5.as_default():
  a = tf.constant([5])
  b = tf.constant([2])
  c = tf.add(a,b)
  d = tf.subtract(a,b)
  
with tf.Session(graph = graph5) as sess:
  result = sess.run(c)
  print ('c =: %s' % result)
  result = sess.run(d)
  print ('d =: %s' % result)

c =: [7]
d =: [3]
